app/Http/routes.php
    Route::post('/users/search', ['as' => 'admin.users.search', 'uses' => 'admin\UserController@search']);
    Route::get('/users/fire/{id}', ['as' => 'admin.users.fire', 'uses' => 'admin\UserController@fire'])->where(['id' => '[0-9]+']);
    Route::get('/users/comments/{id}', ['as' => 'admin.users.comments', 'uses' => 'admin\UserController@comments'])->where(['id' => '[0-9]+']);
    Route::post('/users/comments/{id}/store', ['as' => 'admin.users.comments.store', 'uses' => 'admin\UserController@commentsStore'])->where(['id' => '[0-9]+']);
    Route::get('/users/exclude_from_filter/{filter}', ['uses' => 'admin\UserController@exclude_from_filter']);
    Route::post('/users/apply_changes/', ['uses' => 'admin\UserController@apply_changes']);
    Route::post('/users/accruals', ['uses' => 'admin\UserController@accruals']);
    Route::post('/users/review_add', ['uses' => 'admin\UserController@review_add']);
    Route::post('/users/review_update', ['uses' => 'admin\UserController@review_update']);
    Route::post('/users/review_delete', ['uses' => 'admin\UserController@review_delete']);

    Route::get('/company/fill_by_inn', ['uses' => 'admin\CompanyController@fill_by_inn']);
    Route::get('/companies/search', ['as' => 'admin.companies.search', 'uses' => 'admin\CompanyController@search']);
    Route::resource('companies', 'admin\CompanyController');

    Route::resource('services', 'admin\ServiceController');

    Route::resource('profession', 'admin\ProfessionController');

    Route::resource('products', 'admin\ProductController');

    Route::get('/offers/downloadPDF/{id}', ['as' => 'admin.offers.pdf', 'uses' => 'admin\OfferController@downloadPDF']);
    Route::resource('offers', 'admin\OfferController');

    Route::get('/invoices/downloadPDF/{id}', ['as' => 'admin.invoices.pdf', 'uses' => 'admin\InvoiceController@downloadPDF']);
    Route::get('/invoices/create/{order_id}', ['as' => 'admin.invoices.create', 'uses' => 'admin\InvoiceController@create']);
    Route::resource('invoices', 'admin\InvoiceController', ['except' => ['create']]);

    Route::resource('auto', 'admin\AutoController');
    Route::resource('auto_models', 'admin\AutoModelController');

    Route::get('/sms', ['as' => 'admin.sms.index', 'uses' => 'admin\SmsController@index']);
    Route::get('/sms/{id}', ['as' => 'admin.sms.show', 'uses' => 'admin\SmsController@show'])->where(['id' => '[0-9]+']);

    Route::get('/admin/orders/create/{?company_id}', ['uses' => 'admin\OrderController@create']);
    Route::get('/admin/orders/create/{?contact_id}', ['uses' => 'admin\OrderController@create']);

    Route::resource('orders', 'admin\OrderController', ['except' => ['show']]);

    Route::put('/orders/restore/{id}', ['as' => 'admin.orders.restore', 'uses' => 'admin\OrderController@restore'])->where(['id' => '[0-9]+']);
    Route::put('/orders/staff/{id}', ['as' => 'admin.orders.staff', 'uses' => 'admin\OrderController@staff'])->where(['id' => '[0-9]+']);
    Route::post('/orders/sms', ['as' => 'admin.orders.sms', 'uses' => 'admin\OrderController@sendSms']);
    Route::post('/orders/cancel', ['as' => 'admin.orders.cancel', 'uses' => 'admin\OrderController@cancel']);
    Route::post('/orders/late', ['as' => 'admin.orders.late', 'uses' => 'admin\OrderController@late']);
    Route::get('/orders/exclude_from_filter/{filter}', ['uses' => 'admin\OrderController@exclude_from_filter']);
    Route::post('/orders/set_status', ['as' => 'admin.orders.set_status', 'uses' => 'admin\OrderController@set_status']);
    Route::match(['get', 'post'], '/orders/turn/{length}/{id?}', ['as' => 'admin.orders.turn', 'uses' => 'admin\OrderController@turn']);
    Route::post('/orders/delete_contact', ['uses' => 'admin\OrderController@delete_contact']);
    Route::post('/orders/save_periods', ['uses' => 'admin\OrderController@save_periods']);
    Route::post('/orders/update_ajax', ['uses' => 'admin\OrderController@update_ajax']);
    Route::post('/orders/attach_user', ['uses' => 'admin\OrderController@attach_user']);
    Route::post('/orders/detach_user', ['uses' => 'admin\OrderController@detach_user']);
    Route::post('/orders/create_order_company', ['uses' => 'admin\OrderController@create_order_company']);
    Route::post('/orders/update_calculator', ['uses' => 'admin\OrderController@update_calculator']);
    Route::get('/orders/allCountOfDay', ['uses' => 'admin\OrderController@allCountOfDay']);
    Route::post('/orders/delete_order_company', ['uses' => 'admin\OrderController@delete_order_company']);
    
    Route::post('/metro', ['as' => 'admin.metro.search', 'uses' => 'admin\OrderController@searchMetro']);

    Route::post('/order_companies/update_ajax', ['uses' => 'admin\OrderCompanyController@update_ajax']);
    Route::get('/order_companies/search', ['as' => 'admin.order_companies.search', 'uses' => 'admin\OrderCompanyController@search']);
    Route::resource('order_companies', 'admin\OrderCompanyController');

    Route::post('/order_contacts/update_ajax', ['uses' => 'admin\OrderContactController@update_ajax']);
    Route::post('/order_contacts/attach_to_order', ['uses' => 'admin\OrderContactController@attach_to_order']);
    Route::get('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::resource('order_contacts', 'admin\OrderContactController');
    Route::post('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::get('/order_contacts/get_order_company/{contact_id}', ['uses' => 'admin\OrderContactController@get_order_company']);
    Route::post('/order_contacts/delete_order_company', ['uses' => 'admin\OrderContactController@delete_order_company']);
    
    Route::resource('pages', 'admin\PageController', ['except' => ['show']]);
    Route::get('/pages/{sysname}/edit_sysname', ['as' => 'admin.pages.edit_sysname', 'uses' => 'admin\PageController@editSysname'])->where(['sysname' => '[a-zA-Z0-9_-]+']);
    Route::put('/pages/{sysname}/content', ['as' => 'admin.pages.update_content', 'uses' => 'admin\PageController@updateContent'])->where(['sysname' => '[a-zA-Z0-9_-]+']);

    Route::resource('metatags', 'admin\MetatagsController', ['except' => ['show']]);
    Route::get('/metatags/{route}/edit_route', ['as' => 'admin.metatags.edit_route', 'uses' => 'admin\MetatagsController@editRoute'])->where(['route' => '[\.a-zA-Z0-9_-]+']);

    Route::post('/settings/price', ['as' => 'admin.settings.price', 'uses' => 'admin\SettingController@price']);
    Route::resource('settings', 'admin\SettingController', ['except' => ['show']]);

    Route::get('/image/crop', ['as' => 'admin.image.crop', 'uses' => 'admin\MainController@crop']);
    Route::post('/image/crop', ['as' => 'admin.image.crop.save', 'uses' => 'admin\MainController@cropUpdate']);

    Route::post('/editor/upload', ['as' => 'editor.upload', 'uses' => 'admin\MainController@uploadFileCKeditor'] );

});

// auth
Route::auth();
Route::match(['get', 'head'], '/login', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showLoginForm']);

//Route::match(['get', 'head'], '/register', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showRegistrationForm']);
Route::match(['get', 'post'], '/inn', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@inn']);
Route::match(['get', 'post'], '/smsVerify', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@smsVerify']);
//Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@registrCompany']);
Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthNewController@registerCompany']);
Route::match(['get', 'post'], '/activateEmail', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@activateEmail', 'as' => 'auth.activate.email']);

//Route::match(['get', 'post'], '/resetPass', ['middleware' => 'guest', 'uses' => 'Auth\CleanerController@getPassFromSms']);
Route::match(['get', 'post'], '/cleaner/password/reset', ['middleware' => 'guest', 'as' => 'cleaner.password.reset', 'uses' => 'Auth\CleanerController@password_reset']);
//Route::match(['get', 'post'], '/cleaner/api', ['middleware' => 'guest', 'as' => 'cleaner.api', 'uses' => 'Auth\CleanerController@api']);


/*
* Cleaner
*/

Route::match(['get', 'head'], '/cleaner', ['as' => 'cleaner', 'middleware' => 'guest', 'uses' => 'Auth\CleanerController@loginForm']);
Route::post('/cleaner/login', ['as' => 'cleaner.login', 'uses' => 'Auth\CleanerController@login']);

Route::group(['prefix'=>'cleaner', 'middleware' => 'auth'], function()
{
    Route::get('/main', ['middleware' => 'auth', 'as' => 'cleaner.main', function(){ return redirect()->route('cleaner.tabel'); }]);
    //Route::get('/tabel', ['middleware' => 'auth', 'as' => 'cleaner.tabel', 'uses' => 'cleaner\TabelController@index']);
    Route::get('/tabel/{mobile?}', ['middleware' => 'auth', 'as' => 'cleaner.tabel', 'uses' => 'cleaner\TabelController@index']);
    //Route::get('/mtabel', ['middleware' => 'auth', 'as' => 'cleaner.mtabel', 'uses' => 'cleaner\TabelController@index']);
    
    Route::get('/mutual_settlements', ['as' => 'cleaner.mutual_settlements', 'uses' => 'cleaner\CommonController@mutual_settlements']);
    Route::get('/calendar', ['as' => 'cleaner.calendar', 'uses' => 'cleaner\CommonController@calendar']);

    Route::match(['get', 'post'], '/anketa/edit', ['middleware' => 'auth', 'as' => 'cleaner.anketa.edit', 'uses' => 'cleaner\AnketaController@edit']);
    Route::get('/anketa/show', ['as' => 'cleaner.anketa.view', 'uses' => 'cleaner\AnketaController@show']);

    Route::get('/departures', ['as' => 'cleaner.departures', 'uses' => 'cleaner\DepartureController@index']);
    Route::get('/departures/current', ['as' => 'cleaner.departures.current', 'uses' => 'cleaner\DepartureController@current']);

    Route::get('/orders', ['as' => 'cleaner.orders', 'uses' => 'cleaner\OrderController@index']);

app/Models/OrderContact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Image;
use Storage;

class OrderContact extends Model
{
    use SoftDeletes;

    protected $table = 'order_contacts';

    protected $fillable = [
        'order_company_id', 
        'name', 
        'post', 
        'comments', 
        'user_id',
        'typ',
        'photo',
        'address',
        'apartment',
        'porch',
        'floor',
        'domofon'
    ];

    protected $dates = ['deleted_at'];

    public static $photo_path = 'assets/imgs/contacts/';
    public static $photo_path_preview = 'assets/imgs/contacts/preview/';

    protected static $size_preview_width = 180;
    protected static $size_preview_height = 200;


    public function orders() {
        return $this->belongsToMany('App\Models\Order', 'order_contact', 'contact_id', 'order_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function company()
    {
        return $this->belongsTo('App\Models\OrderCompany', 'order_company_id');
    }

    public function phones() {
        return $this->hasMany('App\Models\OrderContactPhone', 'contact_id');
    }

    public function emails() {
        return $this->hasMany('App\Models\OrderContactEmail', 'contact_id');
    }


    public static function saveImg($request = null, $url = null)
    {
        $arFiles = [];
        //URL в приоритете
        if(!empty($url)) {
        }
        else {
            if( $request->hasFile('photo') && $request->file('photo')->isValid() ) {
                $sizes = getimagesize($request->file('photo')->getRealPath());
                $filename = time().'_'.str_random(5).'.'.$request->file('photo')->getClientOriginalExtension();
                $request->file('photo')->move(public_path(self::$photo_path), $filename);

                //preview
                Image::make(public_path(self::$photo_path).$filename)
                    ->fit(min(self::$size_preview_width, $sizes[0]), min(self::$size_preview_height, $sizes[1]), function ($constraint) {
                        $constraint->upsize();
                    })
                    ->save(public_path(self::$photo_path_preview).$filename);

                $arFiles['photo'] = $filename;
            }

        }

        return $arFiles;
    }

    public function deleteImg() {
        if(!$this->photo) {
            return false;
        }

        Storage::disk('public')->delete([
            $this->getImgPath('photo').$this->photo,
            $this->getImgPreviewPath('photo').$this->photo,
        ]);

        return true;
    }

    public function getImgPath(){
        return self::$photo_path;

    }

    public function getImgPreviewPath(){
        return self::$photo_path_preview;
    }

    public function getPreviewSize($attribute = 'width'){
        $attribute = 'size_preview_'.$attribute;
        return self::$$attribute;
    }
    
}

resources/views/admin/order_contacts/index.blade.php
@extends('admin.layout')
@section('main')
    <input name="_token" type="hidden" value="{{csrf_token()}}">

    <div class="dash-container">
        <div class="dash-content">
            <div class="dash-table" data-item-check="wrap">
                <table>
                    {{--<colgroup>
                        <col class="tbl-check">
                        <col class="tbl-number">
                        <col class="tbl-title">
                        <col class="tbl-contact">
                        <col class="tbl-budget">
                        <col class="tbl-tasks">
                        <col class="tbl-typepay">
                        <col class="tbl-datecreate">
                    </colgroup>--}}
                    <thead>
                    <tr>
                        <td>
                            <label class="o-input-box-replaced"><input type="checkbox" name="items[]" tabindex="0" data-item-check="all-current"><span class="o-input-box-replaced-check"></span></label>
                        </td>
                        <td>
                            <a class="tbl-heads-link" href="#">ФИО</a>
                        </td>
                        <td><a class="tbl-heads-link" href="#">Компания</a></td>
                        <td>Телефон</td>
                        <td>
                            <a class="tbl-heads-link" href="#">Сумма</a>
                            {{--<a href="javascript:void(0);" sort="rating">
                                <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="rating-asc"></i>
                                <i class="fa fa-fw fa-sort-down" sort="rating-desc"></i>
                            </a>--}}
                        </td>
                        <td><a class="tbl-heads-link" href="#">Баланс</a></td>
                        <td><a class="tbl-heads-link" href="#">Email</a></td>
                        <td>
                            <a class="tbl-heads-link" href="#">Дата создания</a>
                        </td>
                        <td><a class="tbl-heads-link" href="#">Ответственный</a></td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($contacts as $item)
                        <tr>
                            <td>
                                <label class="o-input-box-replaced"><input type="checkbox" name="items[]" tabindex="0" data-item-check="current"><span class="o-input-box-replaced-check"></span></label>
                            </td>
                            <td>
                                <a href="{{route('admin.order_contacts.edit', $item->id)}}">{{$item->name}}</a>
                            </td>
                            <td>
                                <a href="{{route('admin.order_companies.edit', @$item->company->id)}}">{{@$item->company->name}}</a>
                            </td>
                            <td>
                                @foreach($item->phones as $phone)
                                    {{$phone->phone}}<br>
                                @endforeach
                            </td>
                            <td>{{number_format($item->orders->sum('amount'), 0, ',', ' ')}}</td>
                            <td>

                            </td>
                            <td>
                                @foreach($item->emails as $email)
                                    {{$email->email}}<br>
                                @endforeach
                            </td>
                            <td>
                                {{date('d.m.Y h:i', strtotime($item->created_at))}}
                            </td>
                            <td>
                                <a href="{{route('admin.users.edit', $item->user_id)}}">{{$item->user->fio()}}</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <div class="paginator-wrap">
                <div class="paginator-block fleft">
                    {{--<div class="paginator-label">Показано {{sizeof($users)}} из {{@$count_users}}</div>--}}
                    <div class="paginator-label">Показано {{sizeof($contacts)}} из {{@$total_contacts_count}}</div>
                </div>
                <div class="paginator-block fright">
                    <div class="paginator-label">Количество записей</div>

                    <div class="pages-list">
                        <ul class="pages-list-ins">
                            <li @if($filters['perpage'] == 10) class="current" @endif><a href="javascript:void(0);" onclick="perpage_pagination(10, 'order_contacts');">10</a></li>
                            <li @if($filters['perpage'] == 25) class="current" @endif><a href="javascript:void(0);" onclick="perpage_pagination(25, 'order_contacts');">25</a></li>
                            <li @if($filters['perpage'] == 50) class="current" @endif><a href="javascript:void(0);" onclick="perpage_pagination(50, 'order_contacts');">50</a></li>
                            <li @if($filters['perpage'] == 100) class="current" @endif><a href="javascript:void(0);" onclick="perpage_pagination(100, 'order_contacts');">100</a></li>
                        </ul>
                    </div>

                    {!! $contacts->render() !!}
                </div>
            </div>

            <div class="dash-container-layer"></div>
        </div>

@stop

resources/views/admin/order_contacts/navbar.blade.php
@if(Route::current()->getName() == 'admin.order_contacts.index')
    <div class="dash-panel-block type-btns">
        <div class="dash-panel-dropdown dropdown-more" data-dropped="wrap">
            <div class="btn-dash-panel-more" data-dropped="btn" data-layer="yes">...</div>
            <div class="dash-panel-dropdown-drop">
                <a href="#">Ссылка 1</a>
                <a href="#">Ссылка 2</a>
                <a href="#">Ссылка 3</a>
            </div>
        </div>

        <a class="o-btn bgs-green o-hvr" href="{{route('admin.order_contacts.create')}}">+ Добавить контакт</a>
    </div>
    <div class="dash-panel-block type-transactions">
        <span class="txt-label">{{@$count_contacts}} контактов:</span>
        <span class="txt-value">{{number_format(@$sum_paginate, 0, ',', ' ')}} руб</span>
    </div>
@elseif(Route::current()->getName() == 'admin.order_contacts.create')
    <div class="dash-panel-title">
        <span class="txt-label">Добавить контакт</span>
    </div>
@elseif(Route::current()->getName() == 'admin.order_contacts.edit')
    <div class="dash-panel-block type-btns">
        <div class="dash-panel-dropdown dropdown-more" data-dropped="wrap">
            <div class="btn-dash-panel-more" data-dropped="btn" data-layer="yes">...</div>
            <div class="dash-panel-dropdown-drop">
                <a href="#">Ссылка 1</a>
                <a href="#">Ссылка 2</a>
                <a href="#">Ссылка 3</a>
            </div>
        </div>

        <div class="dash-panel-dropdown dropdown-more" data-dropped="wrap">
            <div class="o-btn bgs-green o-hvr" data-dropped="btn" data-layer="yes" onclick="window.location.href = '{{route('admin.order_contacts.create')}}';">+ Добавить контакт</div>
            <div class="dash-panel-dropdown-drop">
                <a href="#">Ссылка 1</a>
                <a href="#">Ссылка 2</a>
            </div>
        </div>
    </div>
    <div class="dash-panel-block type-transactions">
        <span class="txt-label">Баланс:</span>
           <span class="txt-value">
              <span class="op-input"><input type="text" placeholder="..." value=""></span>
              руб.</span>
    </div>
@endif

resources/views/admin/order_contacts/orders.blade.php
<div class="dash-table" data-item-check="wrap">
    @can('add', new App\Models\Order())
        <div class="ibox-tools" style="float: right;">
            <a href="{{route('admin.orders.create', ['contact_id' => $contact->id])}}" class="btn btn-success btn-xs">
                <i class="fa fa-plus"></i>
                Добавить заказ
            </a>
        </div>
    @endcan

    @if( !(sizeof($orders) > 0) )
        <p><i>Заказов пока нет...</i></p>
    @else
        <table>
                <colgroup>
                    {{--<col class="tbl-check">--}}
                    <col class="tbl-number">
                    <col class="tbl-title">
                    <col class="tbl-contact">
                    <col class="tbl-budget">
                    <col class="tbl-tasks">
                    <col class="tbl-typework">
                    <col class="tbl-typepay">
                    <col class="tbl-datestart">
                    <col class="tbl-step">
                    <col class="tbl-pay">
                    <col class="tbl-responsible">
                    <col class="tbl-datecreate">
                </colgroup>
                <thead>
                <tr>
                    {{--<td>
                        <label class="o-input-box-replaced"><input type="checkbox" name="items[]" tabindex="0" data-item-check="all-current"><span class="o-input-box-replaced-check"></span></label>
                    </td>--}}
                    <td>№</td>
                    <td>Название</td>
                    <td>Контакт</td>
                    <td><a class="tbl-heads-link" href="#">Бюджет, руб</a></td>
                    <td>Задачи</td>
                    <td>Вид работ</td>
                    <td>Вид оплат</td>
                    <td><a class="tbl-heads-link type-up" href="#">Дата начала</a></td>
                    <td>Этап заказа</td>
                    <td>Оплата</td>
                    <td>Ответственный</td>
                    <td><a class="tbl-heads-link" href="#">Дата создания</a></td>
                </tr>
                </thead>
                <tbody>
                @foreach($orders as $order)
                    <tr>
                        {{--<td>
                            <label class="o-input-box-replaced"><input type="checkbox" name="items[]" tabindex="0" data-item-check="current"><span class="o-input-box-replaced-check"></span></label>
                        </td>--}}
                        <td>{{$order->number}}</td>
                        <td>
                            <a href="{{route('admin.orders.edit', $order->id)}}">{{$order->name}}</a>
                        </td>
                        <td>
                            {{@$order->contacts()->first()->name}}
                            @if(isset($order->orderCompany))
                                <span class="tbl-block-company">“{{$order->orderCompany->name}}”</span>
                            @endif
                        </td>
                        <td>{{number_format($order->amount, 0, ',', ' ')}}</td>
                        <td>Подготовить коммерческое предложение</td>
                        <td>
                            @if( isset($order->calculator) )
                                {{--{{dd($order->calculator)}}--}}
                                {{--{{dump(get_object_vars(\GuzzleHttp\json_decode($order->calculator))['typ'])}}--}}
                                @if(get_object_vars(\GuzzleHttp\json_decode($order->calculator))['typ'] == 82)
                                    ген. уборка
                                @else
                                    послестрой
                                @endif
                            @endif
                        </td>
                        <td>{{--Безналичный--}}</td>
                        <td>{{date('d.m.Y', strtotime($order->date))}}</td>
                        <td>
                                   <span class="pseudo-select" data-pseudo="wrap">
                                       @php
                                           $bg_status_class = '';
                                           switch ($order->status) {
                                               case 'first':
                                                   $bg_status_class = 'bgs-first';
                                                   break;
                                               case 'agree':
                                                   $bg_status_class = 'bgs-agree';
                                                   break;
                                               case 'agreed':
                                                   $bg_status_class = 'bgs-agreed';
                                                   break;
                                               case 'confirmed':
                                                   $bg_status_class = 'bgs-confirmed';
                                                   break;
                                               case 'work':
                                                   $bg_status_class = 'bgs-work';
                                                   break;
                                               case 'performed':
                                                   $bg_status_class = 'bgs-performed';
                                                   break;
                                               case 'final_positive':
                                                   $bg_status_class = 'bgs-final_positive';
                                                   break;
                                               case 'final_negative':
                                                   $bg_status_class = 'bgs-final_negative';
                                                   break;
                                           }
                                       @endphp
                                       <span class="pseudo-select-txt o-btn {{$bg_status_class}}" data-pseudo="title" tabindex="0">{{$order->statusName()}}</span>
                                       <span class="pseudo-select-drop" data-pseudo="drop">
                                            <span data-order_id="{{$order->id}}" data-value="first" data-class="bgs-first" @if($order->status == 'first') class="current" @endif>Первичный контакт</span>
                                            <span data-order_id="{{$order->id}}" data-value="agree" data-class="bgs-agree" @if($order->status == 'agree') class="current" @endif>Согласовать</span>
                                            <span data-order_id="{{$order->id}}" data-value="agreed" data-class="bgs-agreed" @if($order->status == 'agreed') class="current" @endif>Согласованно</span>
                                            <span data-order_id="{{$order->id}}" data-value="confirmed" data-class="bgs-confirmed" @if($order->status == 'confirmed') class="current" @endif>Подтверждено</span>
                                            <span data-order_id="{{$order->id}}" data-value="work" data-class="bgs-work" @if($order->status == 'work') class="current" @endif>В работе</span>
                                            <span data-order_id="{{$order->id}}" data-value="performed" data-class="bgs-performed" @if($order->status == 'performed') class="current" @endif>Работы выполнены</span>
                                            <span data-order_id="{{$order->id}}" data-value="final_positive" data-class="bgs-final_positive" @if($order->status == 'final_positive') class="current" @endif>Успешно реализовано</span>
                                            <span data-order_id="{{$order->id}}" data-value="final_negative" data-class="bgs-final_negative" @if($order->status == 'final_negative') class="current" @endif>Не реализовано</span>
                                       </span>
                                   </span>
                        </td>
                        <td>
                                   <span class="pseudo-select" data-pseudo="wrap">
                                      <span class="pseudo-select-txt" data-pseudo="title" tabindex="0">{{\App\Models\Order::$payStatuses[$order->pay_status]}}</span>
                                      <span class="pseudo-select-drop" data-pseudo="drop">
                                         <span data-order_id="{{$order->id}}" data-value="payed" @if($order->pay_status == 'payed') class="current" @endif>Оплачен</span>
                                         <span data-order_id="{{$order->id}}" data-value="nopayed" @if($order->pay_status == 'nopayed') class="current" @endif>Не оплачен</span>
                                         <span data-order_id="{{$order->id}}" data-value="partpay" @if($order->pay_status == 'partpay') class="current" @endif>Частично оплачен</span>
                                      </span>
                                   </span>
                        </td>
                        <td>
                            @if($order->responsible_users()->count() > 0 )
                                {{$order->responsible_users()->first()->fio()}}
                            @endif
                        </td>
                        <td>{{date('d.m.Y H:i', strtotime($order->created_at))}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
    @endif

</div>