app/Http/routes.php
    Route::resource('users', 'admin\UserController');
    Route::put('/users/restore/{id}', ['as' => 'admin.users.restore', 'uses' => 'admin\UserController@restore'])->where(['id' => '[0-9]+']);
    Route::get('/users/income/{id}', ['as' => 'admin.users.income', 'uses' => 'admin\UserController@income'])->where(['id' => '[0-9]+']);
    Route::post('/users/income/{id}/store', ['as' => 'admin.users.income.store', 'uses' => 'admin\UserController@incomeStore'])->where(['id' => '[0-9]+']);
    Route::delete('/users/income/{id}/delete', ['as' => 'admin.users.income.delete', 'uses' => 'admin\UserController@incomeDelete'])->where(['id' => '[0-9]+']);
    Route::get('/users/outcome/{id}', ['as' => 'admin.users.outcome', 'uses' => 'admin\UserController@outcome'])->where(['id' => '[0-9]+']);
    Route::post('/users/outcome/{id}/store', ['as' => 'admin.users.outcome.store', 'uses' => 'admin\UserController@outcomeStore'])->where(['id' => '[0-9]+']);
    Route::delete('/users/outcome/{id}/delete', ['as' => 'admin.users.outcome.delete', 'uses' => 'admin\UserController@outcomeDelete'])->where(['id' => '[0-9]+']);
    Route::post('/users/outcome/{id}/mass', ['as' => 'admin.users.outcome.mass', 'uses' => 'admin\UserController@outcomeStoreMass'])->where(['id' => '[0-9]+']);
    Route::post('/users/search', ['as' => 'admin.users.search', 'uses' => 'admin\UserController@search']);
    Route::get('/users/fire/{id}', ['as' => 'admin.users.fire', 'uses' => 'admin\UserController@fire'])->where(['id' => '[0-9]+']);
    Route::get('/users/comments/{id}', ['as' => 'admin.users.comments', 'uses' => 'admin\UserController@comments'])->where(['id' => '[0-9]+']);
    Route::post('/users/comments/{id}/store', ['as' => 'admin.users.comments.store', 'uses' => 'admin\UserController@commentsStore'])->where(['id' => '[0-9]+']);
    Route::get('/users/exclude_from_filter/{filter}', ['uses' => 'admin\UserController@exclude_from_filter']);
    Route::post('/users/apply_changes/', ['uses' => 'admin\UserController@apply_changes']);
    Route::post('/users/accruals', ['uses' => 'admin\UserController@accruals']);
    Route::post('/users/review_add', ['uses' => 'admin\UserController@review_add']);
    Route::post('/users/review_update', ['uses' => 'admin\UserController@review_update']);
    Route::post('/users/review_delete', ['uses' => 'admin\UserController@review_delete']);

    Route::get('/company/fill_by_inn', ['uses' => 'admin\CompanyController@fill_by_inn']);
    Route::get('/companies/search', ['as' => 'admin.companies.search', 'uses' => 'admin\CompanyController@search']);
    Route::resource('companies', 'admin\CompanyController');

    Route::resource('services', 'admin\ServiceController');

    Route::resource('profession', 'admin\ProfessionController');

    Route::resource('products', 'admin\ProductController');

    Route::get('/offers/downloadPDF/{id}', ['as' => 'admin.offers.pdf', 'uses' => 'admin\OfferController@downloadPDF']);
    Route::resource('offers', 'admin\OfferController');

    Route::get('/invoices/downloadPDF/{id}', ['as' => 'admin.invoices.pdf', 'uses' => 'admin\InvoiceController@downloadPDF']);
    Route::get('/invoices/create/{order_id}', ['as' => 'admin.invoices.create', 'uses' => 'admin\InvoiceController@create']);
    Route::resource('invoices', 'admin\InvoiceController', ['except' => ['create']]);

    Route::resource('auto', 'admin\AutoController');
    Route::resource('auto_models', 'admin\AutoModelController');

    Route::get('/sms', ['as' => 'admin.sms.index', 'uses' => 'admin\SmsController@index']);
    Route::get('/sms/{id}', ['as' => 'admin.sms.show', 'uses' => 'admin\SmsController@show'])->where(['id' => '[0-9]+']);

    Route::get('/admin/orders/create/{?company_id}', ['uses' => 'admin\OrderController@create']);
    Route::get('/admin/orders/create/{?contact_id}', ['uses' => 'admin\OrderController@create']);

    Route::resource('orders', 'admin\OrderController', ['except' => ['show']]);

    Route::put('/orders/restore/{id}', ['as' => 'admin.orders.restore', 'uses' => 'admin\OrderController@restore'])->where(['id' => '[0-9]+']);
    Route::put('/orders/staff/{id}', ['as' => 'admin.orders.staff', 'uses' => 'admin\OrderController@staff'])->where(['id' => '[0-9]+']);
    Route::post('/orders/sms', ['as' => 'admin.orders.sms', 'uses' => 'admin\OrderController@sendSms']);
    Route::post('/orders/cancel', ['as' => 'admin.orders.cancel', 'uses' => 'admin\OrderController@cancel']);
    Route::post('/orders/late', ['as' => 'admin.orders.late', 'uses' => 'admin\OrderController@late']);
    Route::get('/orders/exclude_from_filter/{filter}', ['uses' => 'admin\OrderController@exclude_from_filter']);
    Route::post('/orders/set_status', ['as' => 'admin.orders.set_status', 'uses' => 'admin\OrderController@set_status']);
    Route::match(['get', 'post'], '/orders/turn/{length}/{id?}', ['as' => 'admin.orders.turn', 'uses' => 'admin\OrderController@turn']);
    Route::post('/orders/delete_contact', ['uses' => 'admin\OrderController@delete_contact']);
    Route::post('/orders/save_periods', ['uses' => 'admin\OrderController@save_periods']);
    Route::post('/orders/update_ajax', ['uses' => 'admin\OrderController@update_ajax']);
    Route::post('/orders/attach_user', ['uses' => 'admin\OrderController@attach_user']);
    Route::post('/orders/detach_user', ['uses' => 'admin\OrderController@detach_user']);
    Route::post('/orders/create_order_company', ['uses' => 'admin\OrderController@create_order_company']);
    Route::post('/orders/update_calculator', ['uses' => 'admin\OrderController@update_calculator']);
    Route::get('/orders/allCountOfDay', ['uses' => 'admin\OrderController@allCountOfDay']);
    Route::post('/orders/delete_order_company', ['uses' => 'admin\OrderController@delete_order_company']);
    
    Route::post('/metro', ['as' => 'admin.metro.search', 'uses' => 'admin\OrderController@searchMetro']);

    Route::post('/order_companies/update_ajax', ['uses' => 'admin\OrderCompanyController@update_ajax']);
    Route::get('/order_companies/search', ['as' => 'admin.order_companies.search', 'uses' => 'admin\OrderCompanyController@search']);
    Route::resource('order_companies', 'admin\OrderCompanyController');

    Route::post('/order_contacts/update_ajax', ['uses' => 'admin\OrderContactController@update_ajax']);
    Route::post('/order_contacts/attach_to_order', ['uses' => 'admin\OrderContactController@attach_to_order']);
    Route::get('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::resource('order_contacts', 'admin\OrderContactController');
    Route::post('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::get('/order_contacts/get_order_company/{contact_id}', ['uses' => 'admin\OrderContactController@get_order_company']);
    Route::post('/order_contacts/delete_order_company', ['uses' => 'admin\OrderContactController@delete_order_company']);
    
    Route::resource('pages', 'admin\PageController', ['except' => ['show']]);
    Route::get('/pages/{sysname}/edit_sysname', ['as' => 'admin.pages.edit_sysname', 'uses' => 'admin\PageController@editSysname'])->where(['sysname' => '[a-zA-Z0-9_-]+']);
    Route::put('/pages/{sysname}/content', ['as' => 'admin.pages.update_content', 'uses' => 'admin\PageController@updateContent'])->where(['sysname' => '[a-zA-Z0-9_-]+']);

    Route::resource('metatags', 'admin\MetatagsController', ['except' => ['show']]);
    Route::get('/metatags/{route}/edit_route', ['as' => 'admin.metatags.edit_route', 'uses' => 'admin\MetatagsController@editRoute'])->where(['route' => '[\.a-zA-Z0-9_-]+']);

    Route::post('/settings/price', ['as' => 'admin.settings.price', 'uses' => 'admin\SettingController@price']);
    Route::resource('settings', 'admin\SettingController', ['except' => ['show']]);

    Route::get('/image/crop', ['as' => 'admin.image.crop', 'uses' => 'admin\MainController@crop']);
    Route::post('/image/crop', ['as' => 'admin.image.crop.save', 'uses' => 'admin\MainController@cropUpdate']);

    Route::post('/editor/upload', ['as' => 'editor.upload', 'uses' => 'admin\MainController@uploadFileCKeditor'] );

});

// auth
Route::auth();
Route::match(['get', 'head'], '/login', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showLoginForm']);

//Route::match(['get', 'head'], '/register', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showRegistrationForm']);
Route::match(['get', 'post'], '/inn', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@inn']);
Route::match(['get', 'post'], '/smsVerify', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@smsVerify']);
//Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@registrCompany']);
Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthNewController@registerCompany']);
Route::match(['get', 'post'], '/activateEmail', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@activateEmail', 'as' => 'auth.activate.email']);

//Route::match(['get', 'post'], '/resetPass', ['middleware' => 'guest', 'uses' => 'Auth\CleanerController@getPassFromSms']);
Route::match(['get', 'post'], '/cleaner/password/reset', ['middleware' => 'guest', 'as' => 'cleaner.password.reset', 'uses' => 'Auth\CleanerController@password_reset']);
//Route::match(['get', 'post'], '/cleaner/api', ['middleware' => 'guest', 'as' => 'cleaner.api', 'uses' => 'Auth\CleanerController@api']);


/*
* Cleaner
*/

Route::match(['get', 'head'], '/cleaner', ['as' => 'cleaner', 'middleware' => 'guest', 'uses' => 'Auth\CleanerController@loginForm']);
Route::post('/cleaner/login', ['as' => 'cleaner.login', 'uses' => 'Auth\CleanerController@login']);

Route::group(['prefix'=>'cleaner', 'middleware' => 'auth'], function()
{

app/Models/Auto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Storage;
use Date;

class Auto extends Model
{
    protected $table = 'autos';

    protected $fillable = ['company_id', 'model_id', 'number', 'date_registration', 'year', 'vin', 'certificate', 'pts', 'contract', 'date_insurance', 'sts'];

    public static $file_path = 'assets/files/autos/';

    public function model() {
        return $this->belongsTo('App\Models\AutoModel', 'model_id');
    }

    public static function saveFile($request = null, $name = 'certificate') {
        if(!$request->hasFile($name) || !$request->file($name)->isValid()) {
            return '';
        }
        $filename = time().'_'.str_random(5).'.'.$request->file($name)->getClientOriginalExtension();
        $request->file($name)->move(public_path(self::$file_path), $filename);
        return $filename;
    }


    public function deleteFile($name) {
        if(!$this->$name){
            return false;
        }

        Storage::disk('public')->delete([
            $this->getFilePath().$this->$name,
            $this->getFilePreviewPath().$this->$name,
        ]);
        return true;
    }

    public function getFilePath(){
        return self::$file_path;
    }

    public function dateRegFormat() {
        if($this->date_registration && $this->date_registration!='0000-00-00') {
            return (new Date($this->date_registration))->format('d.m.Y');
        } else {
            return '';
        }
    }

    public function dateInsuranceFormat() {
        if($this->date_insurance && $this->date_insurance!='0000-00-00') {
            return (new Date($this->date_insurance))->format('d.m.Y');
        } else {
            return '';
        }
    }

}

app/Http/Controllers/admin/AutoController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Auto;
use App\Models\AutoModel;
use Carbon\Carbon;
use Auth;

class AutoController extends Controller
{
    public function __construct() {
        $this->authorize('index', new Auto());
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $filters = $this->getFormFilter($request->input());
        //$autos = Auto::orderBy('id', 'desc')->with('model');

        //sort /*
        //dump($filters); dd();
        if ( isset($filters['order']) && $filters['order']!='')
        {
            //check sql-injection
            $arSort = explode('-', $filters['order']);
            if( strtoupper($arSort[1]) != 'ASC' && strtoupper($arSort[1]) != 'DESC')
                return redirect()->back();

            switch ($arSort[0]) {
                case 'model':
                    $autos = Auto::join('auto_models', 'model_id', '=', 'auto_models.id')
                        ->orderBy('auto_models.name', $arSort[1]);
                    break;
                case 'number':
                    $autos = Auto::orderBy('number', $arSort[1])->with('model');
                    break;
                case 'sts':
                    $autos = Auto::orderBy('sts', $arSort[1])->with('model');
                    break;
                case 'date_registration':
                    $autos = Auto::orderBy('date_registration', $arSort[1])->with('model');
                    break;
                case 'year':
                    $autos = Auto::orderBy('year', $arSort[1])->with('model');
                    break;
                case 'vin':
                    $autos = Auto::orderBy('vin', $arSort[1])->with('model');
                    break;
                case 'date_insurance':
                    $autos = Auto::orderBy('date_insurance', $arSort[1])->with('model');
                    break;
            }
        }
        else
            $autos = Auto::orderBy('id', 'desc')->with('model');
        //sort */
        
        //автомашины только компании пользователя
        $autos = $autos->where('company_id', Auth::user()->company_id);
        $autos = $autos->paginate($filters['perpage'], null, 'page', !empty($filters['page']) ? $filters['page'] : null);

        return view('admin.auto.index', ['autos' => $autos, 'filters' => $filters]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $models = AutoModel::orderBy('name')->get();
        return view('admin.auto.create', ['models' => $models]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\admin\AutoRequest $request)
    {
        $data = $request->all();
        //компания
        $data['company_id'] = Auth::user()->company_id;

        $data['certificate'] = Auto::saveFile($request, 'certificate');
        $data['pts'] = Auto::saveFile($request, 'pts');
        $data['contract'] = Auto::saveFile($request, 'contract');
        if($request->has('date_registration')) {
            $data['date_registration'] = (new Carbon($data['date_registration']))->format('Y.m.d');
        }
        if($request->has('date_insurance')) {
            $data['date_insurance'] = (new Carbon($data['date_insurance']))->format('Y.m.d');
        }

        Auto::create($data);

        return redirect()->route('admin.auto.index')->withMessge('Автомобиль добавлен');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $auto = Auto::where('company_id', Auth::user()->company_id)->findOrFail($id);

        $models = AutoModel::orderBy('name')->get();
        return view('admin.auto.edit', ['auto' => $auto, 'models' => $models]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\admin\AutoRequest $request, $id)
    {
        $data = $request->all();
        $auto = Auto::where('company_id', Auth::user()->company_id)->findOrFail($id);
        if($certificate = Auto::saveFile($request, 'certificate')) {
            $data['certificate'] = $certificate;
            $auto->deleteFile('certificate');
        }
        if($pts = Auto::saveFile($request, 'pts')) {
            $data['pts'] = $pts;
            $auto->deleteFile('pts');
        }
        if($contract = Auto::saveFile($request, 'contract')) {
            $data['contract'] = $contract;
            $auto->deleteFile('contract');
        }
        if($request->has('date_registration')) {
            $data['date_registration'] = (new Carbon($data['date_registration']))->format('Y.m.d');
        }
        if($request->has('date_insurance')) {
            $data['date_insurance'] = (new Carbon($data['date_insurance']))->format('Y.m.d');
        }
        $auto->update($data);

        return redirect()->route('admin.auto.index')->withMessge('Автомобиль изменен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Auto::destroy($id);
        return redirect()->route('admin.auto.index')->withMessage('Автомобиль удален');
    }
}

resources/views/admin/auto/index.blade.php
@extends('admin.layout')
@section('main')

    <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
            try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="{{route('admin.main')}}">Главная</a>
            </li>
            <li class="active">Автомобили</li>
        </ul><!-- /.breadcrumb -->


    </div>

    <div class="page-content">

        <ul class="nav nav-tabs padding-18">
            <li  class="active">
                <a href="{{route('admin.auto.index')}}">
                    Автомобили
                </a>
            </li>
            <li>
                <a href="{{route('admin.auto_models.index')}}">
                    Модели
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active">
                <div class="page-header">
                            <h1>
                                Автомобили
                                <small>
                                    <i class="ace-icon fa fa-angle-double-right"></i>
                                    Список всех автомобилей
                                </small>
                            </h1>
                        </div><!-- /.page-header -->

                        @include('admin.message')

                        <div class="row">
                            <div class="col-xs-12">

                                <div class="table-header">
                                    Список всех автомобилей
                                    <div class="ibox-tools">
                                        <a href="{{route('admin.auto.create')}}" class="btn btn-success btn-xs">
                                            <i class="fa fa-plus"></i>
                                            Добавить автомобиль
                                        </a>
                                    </div>
                                </div>
                                <div>
                                    <div id="dynamic-table_wrapper" class="dataTables_wrapper form-inline no-footer">
                                        <!-- PAGE CONTENT BEGINS -->
                                        <div class="row">

                                            <form method="GET" action="{{route('admin.auto.index')}}">
                                                <input type="hidden" name="f[order]">
                                            </form>

                                            <table id="simple-table" class="table table-striped table-bordered table-hover">
                                                <thead>
                                                <tr>
                                                    <th>
                                                        Модель
                                                        <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="model-asc"></i>
                                                        <i class="fa fa-fw fa-sort-down" sort="model-desc"></i>
                                                    </th>
                                                    <th nowrap>
                                                        Гос. номер
                                                        <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="number-asc"></i>
                                                        <i class="fa fa-fw fa-sort-down" sort="number-desc"></i>
                                                    </th>
                                                    <th>
                                                        СТС №
                                                        <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="sts-asc"></i>
                                                        <i class="fa fa-fw fa-sort-down" sort="sts-desc"></i>
                                                    </th>
                                                    <th>
                                                        Дата постановки на учет
                                                        <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="date_registration-asc"></i>
                                                        <i class="fa fa-fw fa-sort-down" sort="date_registration-desc"></i>
                                                    </th>
                                                    <th nowrap>
                                                        Год выпуска
                                                        <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="year-asc"></i>
                                                        <i class="fa fa-fw fa-sort-down" sort="year-desc"></i>
                                                    </th>
                                                    <th>
                                                        VIN
                                                        <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="vin-asc"></i>
                                                        <i class="fa fa-fw fa-sort-down" sort="vin-desc"></i>
                                                    </th>
                                                    <th>
                                                        Свидетельство о регистрации
                                                    </th>
                                                    <th>
                                                        ПТС
                                                    </th>
                                                    <th>
                                                        Действие строховки
                                                        <i class="fa fa-fw fa-sort-up" style="position: absolute;" sort="date_insurance-asc"></i>
                                                        <i class="fa fa-fw fa-sort-down" sort="date_insurance-desc"></i>
                                                    </th>
                                                    <th></th>
                                                </tr>
                                                </thead>

                                                <tbody>
                                                @forelse($autos as $item)
                                                    <tr>
                                                        <td>{{$item->model->name}}</td>
                                                        <td>
                                                            <a href="{{route('admin.auto.edit', $item->id)}}">{{$item->number}}</a>
                                                        </td>
                                                        <td>{{$item->sts}}</td>
                                                        <td>{{$item->date_registration}}</td>
                                                        <td>{{$item->year}}</td>
                                                        <td>{{$item->vin}}</td>
                                                        <td>
                                                        @if($item->certificate)
                                                            <a href="/{{$item->getFilePath().$item->certificate}}" class="btn btn-xs btn-success">
                                                                <i class="ace-icon glyphicon glyphicon-picture bigger-120"></i>
                                                            </a>
                                                        @endif
                                                        </td>
                                                        <td>
                                                        @if($item->pts)
                                                            <a href="/{{$item->getFilePath().$item->pts}}" class="btn btn-xs btn-success">
                                                                <i class="ace-icon glyphicon glyphicon-picture bigger-120"></i>
                                                            </a>
                                                        @endif
                                                        </td>
                                                        <td>{{$item->date_insurance}}</td>
                                                        <td>
                                                            <div class="hidden-sm hidden-xs btn-group">

                                                                <a class="btn btn-xs btn-info" href="{{route('admin.auto.edit', $item->id)}}">
                                                                    <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                                </a>
                                                                <form method="POST" action='{{route('admin.auto.destroy', $item->id)}}' style="display:inline;">
                                                                    <input type="hidden" name="_method" value="DELETE">
                                                                    <input name="_token" type="hidden" value="{{csrf_token()}}">
                                                                    <button class="btn btn-xs btn-danger action-delete" type="button" style="border-width: 1px;">
                                                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                                    </button>
                                                                </form>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                @empty
                                                    <p>Нет автомобилей</p>
                                                @endforelse
                                                </tbody>
                                            </table>

                                            <div class="row" style="border-bottom:none;">
                                                <div class="col-xs-6">
                                                    <div class="dataTables_paginate paging_simple_numbers" id="dynamic-table_paginate">
                                                        {!! $autos->render() !!}
                                                    </div>
                                                </div>
                                            </div>


                                        </div><!-- /.row -->
                                    </div>
                                </div>

                            </div><!-- /.col -->
                        </div><!-- /.row -->


            </div>
        </div>
    </div><!-- /.page-content -->


@stop