app/Http/routes.php
Route::group(['prefix'=>'admin', 'middleware' => 'auth'], function()
{
    //Route::get('/main', ['as' => 'admin.main', 'uses' => 'admin\MainController@index']);
    Route::get('/main', ['as' => 'admin.main', function(){     return redirect()->route('admin.tabel'); }]);

    Route::get('/tabel', ['as' => 'admin.tabel', 'uses' => 'admin\TabelController@index']);
    Route::get('/calendar', ['as' => 'admin.calendar', 'uses' => 'admin\CalendarController@index']);
    Route::get('/calendar/exclude_from_filter/{filter}', ['uses' => 'admin\CalendarController@exclude_from_filter']);
    Route::get('/calendar/header_info', ['uses' => 'admin\CalendarController@header_info']);

    Route::get('/tabel/get_period_dates/{period}', ['uses' => 'admin\TabelController@get_period_dates']);
    Route::get('/tabel/exclude_from_filter/{filter}', ['uses' => 'admin\TabelController@exclude_from_filter']);

    Route::get('/users/trigger_online/', ['uses' => 'admin\UserController@triggerOnline']);
    Route::resource('users', 'admin\UserController');
    Route::put('/users/restore/{id}', ['as' => 'admin.users.restore', 'uses' => 'admin\UserController@restore'])->where(['id' => '[0-9]+']);
    Route::get('/users/income/{id}', ['as' => 'admin.users.income', 'uses' => 'admin\UserController@income'])->where(['id' => '[0-9]+']);
    Route::post('/users/income/{id}/store', ['as' => 'admin.users.income.store', 'uses' => 'admin\UserController@incomeStore'])->where(['id' => '[0-9]+']);
    Route::delete('/users/income/{id}/delete', ['as' => 'admin.users.income.delete', 'uses' => 'admin\UserController@incomeDelete'])->where(['id' => '[0-9]+']);
    Route::get('/users/outcome/{id}', ['as' => 'admin.users.outcome', 'uses' => 'admin\UserController@outcome'])->where(['id' => '[0-9]+']);
    Route::post('/users/outcome/{id}/store', ['as' => 'admin.users.outcome.store', 'uses' => 'admin\UserController@outcomeStore'])->where(['id' => '[0-9]+']);
    Route::delete('/users/outcome/{id}/delete', ['as' => 'admin.users.outcome.delete', 'uses' => 'admin\UserController@outcomeDelete'])->where(['id' => '[0-9]+']);
    Route::post('/users/outcome/{id}/mass', ['as' => 'admin.users.outcome.mass', 'uses' => 'admin\UserController@outcomeStoreMass'])->where(['id' => '[0-9]+']);
    Route::post('/users/search', ['as' => 'admin.users.search', 'uses' => 'admin\UserController@search']);
    Route::get('/users/fire/{id}', ['as' => 'admin.users.fire', 'uses' => 'admin\UserController@fire'])->where(['id' => '[0-9]+']);
    Route::get('/users/comments/{id}', ['as' => 'admin.users.comments', 'uses' => 'admin\UserController@comments'])->where(['id' => '[0-9]+']);
    Route::post('/users/comments/{id}/store', ['as' => 'admin.users.comments.store', 'uses' => 'admin\UserController@commentsStore'])->where(['id' => '[0-9]+']);
    Route::get('/users/exclude_from_filter/{filter}', ['uses' => 'admin\UserController@exclude_from_filter']);
    Route::post('/users/apply_changes/', ['uses' => 'admin\UserController@apply_changes']);
    Route::post('/users/accruals', ['uses' => 'admin\UserController@accruals']);
    Route::post('/users/review_add', ['uses' => 'admin\UserController@review_add']);
    Route::post('/users/review_update', ['uses' => 'admin\UserController@review_update']);
    Route::post('/users/review_delete', ['uses' => 'admin\UserController@review_delete']);

    Route::get('/company/fill_by_inn', ['uses' => 'admin\CompanyController@fill_by_inn']);
    Route::get('/companies/search', ['as' => 'admin.companies.search', 'uses' => 'admin\CompanyController@search']);
    Route::resource('companies', 'admin\CompanyController');

    Route::resource('services', 'admin\ServiceController');

    Route::resource('profession', 'admin\ProfessionController');

    Route::resource('products', 'admin\ProductController');

    Route::get('/offers/downloadPDF/{id}', ['as' => 'admin.offers.pdf', 'uses' => 'admin\OfferController@downloadPDF']);
    Route::resource('offers', 'admin\OfferController');

    Route::get('/invoices/downloadPDF/{id}', ['as' => 'admin.invoices.pdf', 'uses' => 'admin\InvoiceController@downloadPDF']);
    Route::get('/invoices/create/{order_id}', ['as' => 'admin.invoices.create', 'uses' => 'admin\InvoiceController@create']);
    Route::resource('invoices', 'admin\InvoiceController', ['except' => ['create']]);

    Route::resource('auto', 'admin\AutoController');
    Route::resource('auto_models', 'admin\AutoModelController');

    Route::get('/sms', ['as' => 'admin.sms.index', 'uses' => 'admin\SmsController@index']);
    Route::get('/sms/{id}', ['as' => 'admin.sms.show', 'uses' => 'admin\SmsController@show'])->where(['id' => '[0-9]+']);

    Route::get('/admin/orders/create/{?company_id}', ['uses' => 'admin\OrderController@create']);
    Route::get('/admin/orders/create/{?contact_id}', ['uses' => 'admin\OrderController@create']);

    Route::resource('orders', 'admin\OrderController', ['except' => ['show']]);

    Route::put('/orders/restore/{id}', ['as' => 'admin.orders.restore', 'uses' => 'admin\OrderController@restore'])->where(['id' => '[0-9]+']);
    Route::put('/orders/staff/{id}', ['as' => 'admin.orders.staff', 'uses' => 'admin\OrderController@staff'])->where(['id' => '[0-9]+']);
    Route::post('/orders/sms', ['as' => 'admin.orders.sms', 'uses' => 'admin\OrderController@sendSms']);
    Route::post('/orders/cancel', ['as' => 'admin.orders.cancel', 'uses' => 'admin\OrderController@cancel']);
    Route::post('/orders/late', ['as' => 'admin.orders.late', 'uses' => 'admin\OrderController@late']);
    Route::get('/orders/exclude_from_filter/{filter}', ['uses' => 'admin\OrderController@exclude_from_filter']);
    Route::post('/orders/set_status', ['as' => 'admin.orders.set_status', 'uses' => 'admin\OrderController@set_status']);
    Route::match(['get', 'post'], '/orders/turn/{length}/{id?}', ['as' => 'admin.orders.turn', 'uses' => 'admin\OrderController@turn']);
    Route::post('/orders/delete_contact', ['uses' => 'admin\OrderController@delete_contact']);
    Route::post('/orders/save_periods', ['uses' => 'admin\OrderController@save_periods']);
    Route::post('/orders/update_ajax', ['uses' => 'admin\OrderController@update_ajax']);
    Route::post('/orders/attach_user', ['uses' => 'admin\OrderController@attach_user']);
    Route::post('/orders/detach_user', ['uses' => 'admin\OrderController@detach_user']);
    Route::post('/orders/create_order_company', ['uses' => 'admin\OrderController@create_order_company']);
    Route::post('/orders/update_calculator', ['uses' => 'admin\OrderController@update_calculator']);
    Route::get('/orders/allCountOfDay', ['uses' => 'admin\OrderController@allCountOfDay']);
    Route::post('/orders/delete_order_company', ['uses' => 'admin\OrderController@delete_order_company']);
    
    Route::post('/metro', ['as' => 'admin.metro.search', 'uses' => 'admin\OrderController@searchMetro']);

    Route::post('/order_companies/update_ajax', ['uses' => 'admin\OrderCompanyController@update_ajax']);
    Route::get('/order_companies/search', ['as' => 'admin.order_companies.search', 'uses' => 'admin\OrderCompanyController@search']);
    Route::resource('order_companies', 'admin\OrderCompanyController');

    Route::post('/order_contacts/update_ajax', ['uses' => 'admin\OrderContactController@update_ajax']);
    Route::post('/order_contacts/attach_to_order', ['uses' => 'admin\OrderContactController@attach_to_order']);
    Route::get('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::resource('order_contacts', 'admin\OrderContactController');
    Route::post('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::get('/order_contacts/get_order_company/{contact_id}', ['uses' => 'admin\OrderContactController@get_order_company']);
    Route::post('/order_contacts/delete_order_company', ['uses' => 'admin\OrderContactController@delete_order_company']);
    
    Route::resource('pages', 'admin\PageController', ['except' => ['show']]);
    Route::get('/pages/{sysname}/edit_sysname', ['as' => 'admin.pages.edit_sysname', 'uses' => 'admin\PageController@editSysname'])->where(['sysname' => '[a-zA-Z0-9_-]+']);
    Route::put('/pages/{sysname}/content', ['as' => 'admin.pages.update_content', 'uses' => 'admin\PageController@updateContent'])->where(['sysname' => '[a-zA-Z0-9_-]+']);

    Route::resource('metatags', 'admin\MetatagsController', ['except' => ['show']]);
    Route::get('/metatags/{route}/edit_route', ['as' => 'admin.metatags.edit_route', 'uses' => 'admin\MetatagsController@editRoute'])->where(['route' => '[\.a-zA-Z0-9_-]+']);

    Route::post('/settings/price', ['as' => 'admin.settings.price', 'uses' => 'admin\SettingController@price']);
    Route::resource('settings', 'admin\SettingController', ['except' => ['show']]);

    Route::get('/image/crop', ['as' => 'admin.image.crop', 'uses' => 'admin\MainController@crop']);
    Route::post('/image/crop', ['as' => 'admin.image.crop.save', 'uses' => 'admin\MainController@cropUpdate']);

    Route::post('/editor/upload', ['as' => 'editor.upload', 'uses' => 'admin\MainController@uploadFileCKeditor'] );

});

// auth
Route::auth();
Route::match(['get', 'head'], '/login', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showLoginForm']);

//Route::match(['get', 'head'], '/register', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showRegistrationForm']);
Route::match(['get', 'post'], '/inn', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@inn']);
Route::match(['get', 'post'], '/smsVerify', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@smsVerify']);
//Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@registrCompany']);
Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthNewController@registerCompany']);

app/Http/Controllers/admin/CompanyController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Company;
use Auth;

class CompanyController extends Controller
{
    public function __construct() {
        //$this->authorize('index', new Company());
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if( !$this->authorize('index', new Company()) )
            return redirect()->back(403);
        
        $filters = $this->getFormFilter($request->input());

        $companies = Company::orderBy('id', 'desc');
        if (!empty($filters) && !empty($filters['name'])) {
            $companies->where('name', 'LIKE', '%'.$filters['name'].'%');
        }
        if (!empty($filters) && !empty($filters['inn'])) {
            $companies->where('inn', 'LIKE', '%'.$filters['inn'].'%');
        }
        $companies = $companies->paginate($filters['perpage'], null, 'page', !empty($filters['page']) ? $filters['page'] : null);

        return view('admin.companies.index', ['companies' => $companies, 'filters' => $filters]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if( !$this->authorize('index', new Company()) )
            return redirect()->back(403);

        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\admin\CompanyInsertRequest $request)
    {
        if( !$this->authorize('index', new Company()) )
            return redirect()->back(403);

        $data = $request->all();
        $company = Company::create(['name' => $data['company'], 'inn' => $data['inn']]);

        $group = \App\Models\UserGroup::where('Name', 'Admin')->first();

        $data['company_id'] = $company->id;
        $data['group_id'] = $group->id;
        $data['status'] = 1;
        if($data['password']) {
            $data['password'] = bcrypt($data['password']);
        }
        $user = \App\User::create($data);

        //связь с телефонами
        if($request->has('phones')) {
            foreach($request->input('phones') as  $phone) {
                $number = substr(preg_replace('|[^0-9]+|','',$phone), -10, 10);
                $user->phones()->create(['phone' => $phone, 'number' => $number]);
            }
        }

        return redirect()->route('admin.companies.index')->withMessge('Компания и Администратор добавлены');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        /*if( !$this->authorize('update', new Company()) )
            return redirect()->back(403);*/
        if( !$this->authorize('index', new Company()) )
            return redirect()->back(403);

        $company = Company::find($id);
        return view('admin.companies.edit', ['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\admin\CompanyRequest $request, $id)
    {
        //dd($request->file('logo'));
        //dd($_FILES);
        if ( !$request->user()->can('index', new Company()) ) {
            if (!$this->authorize('update', new Company()) OR $request->user()->company_id != $id)
                return redirect()->back(403);
        }

        $data = $request->all();
        //$data = $request->except('logo');
        $company = Company::findOrFail($id);

        $arImgs = Company::saveImg($request);
        if( !empty($arImgs) ) {
            if(isset($arImgs['stamp'])) {
                $data['stamp'] = $arImgs['stamp'];
                $company->deleteImg('stamp');                
            }
            if(isset($arImgs['signature'])) {
                $data['signature'] = $arImgs['signature'];
                $company->deleteImg('signature');
            }
            if(isset($arImgs['logo'])) {
                //unset($data['logo']);
                $data['logo'] = $arImgs['logo'];
                $company->deleteImg('logo');
            }
        } else {
            if($request->file('logo') || $request->file('stamp') || $request->file('signature'))
                return redirect()->back()->withErrors(['Файл слишком большой!'])->withInput();
        }

        $company->update($data);

        //return redirect()->route('admin.companies.index')->withMessge('Компания изменена');
        return redirect()->back()->withMessge('Компания изменена');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Company::destroy($id);
        return redirect()->route('admin.companies.index')->withMessage('Компания удалена');
    }
    
    //
    public function fill_by_inn(Request $request) {
        $dataCompany = Company::getCompanyDataByInn($request->inn, 'ajax');
        //dd($dataCompany);
        echo json_encode($dataCompany);
    }

    /**
     * search autocomplete
     */
    public function search(Request $request) {
        $data =[];
        if($request->has('term') && $request->input('term')) {
            if(Auth::user()->company) {
                /*$companies = Company::where('name', 'LIKE', $request->input('term') . '%')
                    ->where('id', Auth::user()->company_id)
                    ->orderBy('name')->take(10)->get();*/
                $companies = Company::where('id', Auth::user()->company_id)
                    ->where('name', 'LIKE', $request->input('term') . '%')
                    ->orderBy('name')->take(10)->get();
            } else {
                $companies = Company::where('name', 'LIKE', $request->input('term') . '%')
                    ->orderBy('name')->take(10)->get();
            }

            //$companies = $companies->orderBy('name')->take(10)->get();

            foreach ($companies as $company) {
                $item = [
                    'id' => $company->id,
                    'name' => $company->name,
                    'site' => $company->site,
                    'phone' => $company->phone,
                    'email' => $company->email,
                ];
                $data[] = $item;
            }
        }

        return response()->json($data);
    }

}

resources/views/admin/companies/company_tab_main.blade.php
<div class="kp-order-form-wrap">

    <form class="form-horizontal" role="form" action="{{route('admin.companies.update', $company->id)}}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PUT">
        <input name="_token" type="hidden" value="{{csrf_token()}}">

        <input name="typ" type="hidden" value="{{$company->typ}}">
        <input name="name" type="hidden" value="{{$company->name}}">
        <input name="inn" type="hidden" value="{{$company->inn}}">

        <div class="p-company-heads clearfix">
            <div class="p-company-heads-fields">
                <div class="kp-order-box-toggle-fields type-company" data-addfieldbox-tgl-show="wrap">

                    <div class="kp-order-box-toggle-fields-row">
                        <div class="op-input-label">Сайт:</div>
                        <div class="op-input type-btns" data-op-input="item">
                            <input type="text" placeholder="..." data-op-input="get" data-name="www" name="site" value="{{ old('site', $company->site) }}">
                        </div>
                    </div>
                    <div class="kp-order-box-toggle-fields-row">
                        <div class="op-input-label">Телефон:</div>
                        <div class="op-input type-btns" data-op-input="item">
                            <input type="text" placeholder="..." data-op-input="get" data-jsmask="tel" data-name="tel" name="phone" value="{{ old('phone', $company->phone) }}">
                        </div>
                    </div>
                    <div class="kp-order-box-toggle-fields-row">
                        <div class="op-input-label">E-mail:</div>
                        <div class="op-input type-btns" data-op-input="item">
                            <input type="text" placeholder="..." data-op-input="get" data-name="email" name="email" value="{{ old('email', $company->email) }}">
                        </div>
                    </div>

                    {{--<div class="kp-order-box-toggle-fields-tgl" data-addfieldbox-tgl-show="field" style="display: none;">
                        <div class="kp-order-box-toggle-fields-row">
                            <div class="op-input-label">Поле 1:</div>
                            <div class="op-input type-btns" data-op-input="item">
                                <input type="text" placeholder="..." data-op-input="get" value="">
                            </div>
                        </div>
                    </div>
                    <div class="kp-order-box-toggle-fields-tgl" data-addfieldbox-tgl-show="field" style="display: none;">
                        <div class="kp-order-box-toggle-fields-row">
                            <div class="op-input-label">Поле 2:</div>
                            <div class="op-input type-btns" data-op-input="item">
                                <input type="text" placeholder="..." data-op-input="get" value="">
                            </div>
                        </div>
                    </div>
                    <div class="kp-order-box-toggle-fields-tgl" data-addfieldbox-tgl-show="field" style="display: none;">
                        <div class="kp-order-box-toggle-fields-row">
                            <div class="op-input-label">Поле 3:</div>
                            <div class="op-input type-btns" data-op-input="item">
                                <input type="text" placeholder="..." data-op-input="get" value="">
                            </div>
                        </div>
                    </div>

                    <div class="kp-order-box-toggle-fields-adds">
                        <div class="adds-down-btn" data-addfieldbox-tgl-show="btn">
                            <span class="txt-label">Еще</span>
                            <div class="adds-down-btn-icon">
                                <span class="icon-input-ctrl-down"></span>
                                <span class="icon-input-ctrl-down-h btn-hover"></span>
                            </div>
                        </div>
                    </div>--}}
                </div>
            </div>
            <div class="p-company-heads-right">

                <div class="p-company-heads-logo-block type-uploads" data-contact-block-logo="wrap">
                    <div class="p-company-heads-nologo">
                        <label class="p-company-heads-logo-add">
                            <input name="logo" type="file" data-contact-block-logo="upload" accept="image/*">
                        </label>
                    </div>
                    <span class="p-company-heads-logo" data-contact-block-logo="image">
                        {{--<img src="img/blank/page-company-logo-lizing.png" alt="">--}}
                        <img src="/assets/imgs/companies/logo/{{$company->logo}}">
                    </span>
                    <div class="p-company-heads-logo-control">
                        <div class="op-input-control-btn" data-contact-block-logo="remove"><span class="icon-input-ctrl-clear"></span><span class="icon-input-ctrl-clear-h btn-hover"></span></div>
                    </div>
                </div>
            </div>
        </div>


        <div class="kp-order-form-row clearfix type-address">
            <div class="kp-order-form-labinput">
                <div class="op-input-label">Адрес:</div>
                <div class="kp-order-form-labinput-box">
                    <div class="op-input type-btns" data-op-input="item" data-openside>
                        <div class="op-input-control-btn" data-op-input="search">
                            <span class="icon-input-ctrl-search"></span>
                            <span class="icon-input-ctrl-search-h btn-hover"></span>
                        </div>
                        <input type="text" placeholder="..." data-op-input="get" data-openside-map="#side-ya-map" name="address" value="{{ old('address', $company->address) }}">
                    </div>
                </div>
            </div>
        </div>

        <div class="kp-order-form-row clearfix type-addressdetail">
            <div class="kp-order-form-justify">
                <div class="kp-order-form-justify-ins">
                    <div class="kp-order-form-justify-item">
                        <div class="op-input-label">Строение:</div>
                        <div class="op-input">
                            <input type="text" placeholder="..." name="building" value="{{ old('building', $company->building)}}">
                        </div>
                    </div>
                    <div class="kp-order-form-justify-item">
                        <div class="op-input-label">Корпус:</div>
                        <div class="op-input">
                            <input type="text" placeholder="..." name="housing" value="{{ old('housing', $company->housing)}}">
                        </div>
                    </div>
                    <div class="kp-order-form-justify-item">
                        <div class="op-input-label">Офис:</div>
                        <div class="op-input">
                            <input type="text" placeholder="..." name="office" value="{{ old('office', $company->office) }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="kp-order-form-row clearfix type-note">
            <div class="op-input-label">Примечание:</div>
            <div class="op-input">
                <textarea placeholder="..." data-autoheight="true" name="comments">{{ old('comments', $company->comments) }}</textarea>
            </div>
        </div>

        <div class="kp-order-form-row clearfix type-person">
            <div class="kp-order-form-labinput">
                <div class="op-input-label">Ответственный:</div>
                <div class="kp-order-form-labinput-box" data-persons="wrap" id="kp-order-person-setitem">
                    {{--<div class="op-input type-btns" data-op-input="item">
                        <div class="op-input-control-btn" data-op-input="add_person">
                            <span class="icon-input-ctrl-down"></span>
                            <span class="icon-input-ctrl-down-h btn-hover"></span>
                        </div>
                        <div class="op-input-control-btn" data-op-input="search">
                            <span class="icon-input-ctrl-search"></span>
                            <span class="icon-input-ctrl-search-h btn-hover"></span>
                        </div>
                        <input type="text" placeholder="..." value="" data-op-input="get" id="js-kp-order-person-search">
                    </div>--}}

                    <div class="kp-order-form-person-item" data-persons="item">
                        {{--<div class="kp-order-form-person-item-ava" style="background-image:url(img/blank/avatar.png)"></div>--}}
                        <div class="kp-order-form-person-item-ava" style="background-image:url({{'/'.\App\User::$img_path_preview.$company->user_avatar}})"></div>
                        <div class="kp-order-form-person-item-name">{{$company->user_surname.($company->user_name ? ' '.$company->user_name : '').($company->user_patronicname ? ' '.$company->user_patronicname : '')}}</div>
                        {{--<div class="kp-order-form-person-item-remove" data-persons="remove"></div>--}}
                    </div>
                </div>
            </div>
        </div>

        <script type="text/template" id="kp-order-person-additem">
            <div class="kp-order-form-person-item" data-persons="item">
                <div class="kp-order-form-person-item-ava" style="background-image:url([avatar])"></div>
                <div class="kp-order-form-person-item-name">[name]</div>
                <div class="kp-order-form-person-item-remove" data-persons="remove"></div>
            </div>
        </script>

        <div class="page-kp-form-bottom-button type-right">
            {{--<span class="page-kp-form-button bgs-green">Сохранить</span>--}}
            <button class="page-kp-form-button bgs-green" type="submit">Сохранить</button>
            <span class="page-kp-form-button bgs-orange">Обновить</span>
        </div>

    </form>
</div>

resources/views/admin/companies/edit.blade.php
@extends('admin.layout')
@section('main')
    <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
            try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="{{route('admin.main')}}">Главная</a>
            </li>

            <li>
                <a href="{{route('admin.companies.index')}}">Компании</a>
            </li>
            <li class="active">Редактирование компании</li>
        </ul><!-- /.breadcrumb -->


    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Компании
                <small>
                    <i class="ace-icon fa fa-angle-double-right"></i>
                    Редактирование
                </small>
            </h1>
        </div><!-- /.page-header -->

        @include('admin.message')

        <div class="row">
            <div class="col-xs-12">
                <!-- PAGE CONTENT BEGINS -->
                <form class="form-horizontal" role="form" action="{{route('admin.companies.update', $company->id)}}" method="POST" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="PUT">
                    <input name="_token" type="hidden" value="{{csrf_token()}}">

                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-0"> Название </label>
                        <div class="col-sm-9">
                            <input type="text" id="form-field-0" name="name" placeholder="Название" value="{{ old('name', $company->name) }}" class="col-sm-5">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> ИНН </label>
                        <div class="col-sm-9">
                            <input type="text" id="form-field-1" name="inn" placeholder="ИНН" value="{{ old('inn', $company->inn) }}" class="col-sm-5">
                        </div>
                    </div>
                    <div class="col-md-offset-3 col-md-9">
                        <button class="btn btn-success" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            Сохранить
                        </button>
                        &nbsp; &nbsp; &nbsp;
                        <button class="btn" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            Обновить
                        </button>
                        &nbsp; &nbsp; &nbsp;
                        <a class="btn btn-info" href="{{route('admin.companies.index')}}">
                            <i class="ace-icon glyphicon glyphicon-backward bigger-110"></i>
                            Назад
                        </a>
                    </div>
                </form>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
@stop