app/Http/routes.php
    Route::post('/users/search', ['as' => 'admin.users.search', 'uses' => 'admin\UserController@search']);
    Route::get('/users/fire/{id}', ['as' => 'admin.users.fire', 'uses' => 'admin\UserController@fire'])->where(['id' => '[0-9]+']);
    Route::get('/users/comments/{id}', ['as' => 'admin.users.comments', 'uses' => 'admin\UserController@comments'])->where(['id' => '[0-9]+']);
    Route::post('/users/comments/{id}/store', ['as' => 'admin.users.comments.store', 'uses' => 'admin\UserController@commentsStore'])->where(['id' => '[0-9]+']);
    Route::get('/users/exclude_from_filter/{filter}', ['uses' => 'admin\UserController@exclude_from_filter']);
    Route::post('/users/apply_changes/', ['uses' => 'admin\UserController@apply_changes']);
    Route::post('/users/accruals', ['uses' => 'admin\UserController@accruals']);
    Route::post('/users/review_add', ['uses' => 'admin\UserController@review_add']);
    Route::post('/users/review_update', ['uses' => 'admin\UserController@review_update']);
    Route::post('/users/review_delete', ['uses' => 'admin\UserController@review_delete']);

    Route::get('/company/fill_by_inn', ['uses' => 'admin\CompanyController@fill_by_inn']);
    Route::get('/companies/search', ['as' => 'admin.companies.search', 'uses' => 'admin\CompanyController@search']);
    Route::resource('companies', 'admin\CompanyController');

    Route::resource('services', 'admin\ServiceController');

    Route::resource('profession', 'admin\ProfessionController');

    Route::resource('products', 'admin\ProductController');

    Route::get('/offers/downloadPDF/{id}', ['as' => 'admin.offers.pdf', 'uses' => 'admin\OfferController@downloadPDF']);
    Route::resource('offers', 'admin\OfferController');

    Route::get('/invoices/downloadPDF/{id}', ['as' => 'admin.invoices.pdf', 'uses' => 'admin\InvoiceController@downloadPDF']);
    Route::get('/invoices/create/{order_id}', ['as' => 'admin.invoices.create', 'uses' => 'admin\InvoiceController@create']);
    Route::resource('invoices', 'admin\InvoiceController', ['except' => ['create']]);

    Route::resource('auto', 'admin\AutoController');
    Route::resource('auto_models', 'admin\AutoModelController');

    Route::get('/sms', ['as' => 'admin.sms.index', 'uses' => 'admin\SmsController@index']);
    Route::get('/sms/{id}', ['as' => 'admin.sms.show', 'uses' => 'admin\SmsController@show'])->where(['id' => '[0-9]+']);

    Route::get('/admin/orders/create/{?company_id}', ['uses' => 'admin\OrderController@create']);
    Route::get('/admin/orders/create/{?contact_id}', ['uses' => 'admin\OrderController@create']);

    Route::resource('orders', 'admin\OrderController', ['except' => ['show']]);

    Route::put('/orders/restore/{id}', ['as' => 'admin.orders.restore', 'uses' => 'admin\OrderController@restore'])->where(['id' => '[0-9]+']);
    Route::put('/orders/staff/{id}', ['as' => 'admin.orders.staff', 'uses' => 'admin\OrderController@staff'])->where(['id' => '[0-9]+']);
    Route::post('/orders/sms', ['as' => 'admin.orders.sms', 'uses' => 'admin\OrderController@sendSms']);
    Route::post('/orders/cancel', ['as' => 'admin.orders.cancel', 'uses' => 'admin\OrderController@cancel']);
    Route::post('/orders/late', ['as' => 'admin.orders.late', 'uses' => 'admin\OrderController@late']);
    Route::get('/orders/exclude_from_filter/{filter}', ['uses' => 'admin\OrderController@exclude_from_filter']);
    Route::post('/orders/set_status', ['as' => 'admin.orders.set_status', 'uses' => 'admin\OrderController@set_status']);
    Route::match(['get', 'post'], '/orders/turn/{length}/{id?}', ['as' => 'admin.orders.turn', 'uses' => 'admin\OrderController@turn']);
    Route::post('/orders/delete_contact', ['uses' => 'admin\OrderController@delete_contact']);
    Route::post('/orders/save_periods', ['uses' => 'admin\OrderController@save_periods']);
    Route::post('/orders/update_ajax', ['uses' => 'admin\OrderController@update_ajax']);
    Route::post('/orders/attach_user', ['uses' => 'admin\OrderController@attach_user']);
    Route::post('/orders/detach_user', ['uses' => 'admin\OrderController@detach_user']);
    Route::post('/orders/create_order_company', ['uses' => 'admin\OrderController@create_order_company']);
    Route::post('/orders/update_calculator', ['uses' => 'admin\OrderController@update_calculator']);
    Route::get('/orders/allCountOfDay', ['uses' => 'admin\OrderController@allCountOfDay']);
    Route::post('/orders/delete_order_company', ['uses' => 'admin\OrderController@delete_order_company']);
    
    Route::post('/metro', ['as' => 'admin.metro.search', 'uses' => 'admin\OrderController@searchMetro']);

    Route::post('/order_companies/update_ajax', ['uses' => 'admin\OrderCompanyController@update_ajax']);
    Route::get('/order_companies/search', ['as' => 'admin.order_companies.search', 'uses' => 'admin\OrderCompanyController@search']);
    Route::resource('order_companies', 'admin\OrderCompanyController');

    Route::post('/order_contacts/update_ajax', ['uses' => 'admin\OrderContactController@update_ajax']);
    Route::post('/order_contacts/attach_to_order', ['uses' => 'admin\OrderContactController@attach_to_order']);
    Route::get('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::resource('order_contacts', 'admin\OrderContactController');
    Route::post('/order_contacts/search', ['as' => 'admin.order_contacts.search', 'uses' => 'admin\OrderContactController@search']);
    Route::get('/order_contacts/get_order_company/{contact_id}', ['uses' => 'admin\OrderContactController@get_order_company']);
    Route::post('/order_contacts/delete_order_company', ['uses' => 'admin\OrderContactController@delete_order_company']);
    
    Route::resource('pages', 'admin\PageController', ['except' => ['show']]);
    Route::get('/pages/{sysname}/edit_sysname', ['as' => 'admin.pages.edit_sysname', 'uses' => 'admin\PageController@editSysname'])->where(['sysname' => '[a-zA-Z0-9_-]+']);
    Route::put('/pages/{sysname}/content', ['as' => 'admin.pages.update_content', 'uses' => 'admin\PageController@updateContent'])->where(['sysname' => '[a-zA-Z0-9_-]+']);

    Route::resource('metatags', 'admin\MetatagsController', ['except' => ['show']]);
    Route::get('/metatags/{route}/edit_route', ['as' => 'admin.metatags.edit_route', 'uses' => 'admin\MetatagsController@editRoute'])->where(['route' => '[\.a-zA-Z0-9_-]+']);

    Route::post('/settings/price', ['as' => 'admin.settings.price', 'uses' => 'admin\SettingController@price']);
    Route::resource('settings', 'admin\SettingController', ['except' => ['show']]);

    Route::get('/image/crop', ['as' => 'admin.image.crop', 'uses' => 'admin\MainController@crop']);
    Route::post('/image/crop', ['as' => 'admin.image.crop.save', 'uses' => 'admin\MainController@cropUpdate']);

    Route::post('/editor/upload', ['as' => 'editor.upload', 'uses' => 'admin\MainController@uploadFileCKeditor'] );

});

// auth
Route::auth();
Route::match(['get', 'head'], '/login', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showLoginForm']);

//Route::match(['get', 'head'], '/register', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@showRegistrationForm']);
Route::match(['get', 'post'], '/inn', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@inn']);
Route::match(['get', 'post'], '/smsVerify', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@smsVerify']);
//Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@registrCompany']);
Route::match(['get', 'post'], '/register_company', ['middleware' => 'guest', 'uses' => 'Auth\AuthNewController@registerCompany']);
Route::match(['get', 'post'], '/activateEmail', ['middleware' => 'guest', 'uses' => 'Auth\AuthController@activateEmail', 'as' => 'auth.activate.email']);

//Route::match(['get', 'post'], '/resetPass', ['middleware' => 'guest', 'uses' => 'Auth\CleanerController@getPassFromSms']);
Route::match(['get', 'post'], '/cleaner/password/reset', ['middleware' => 'guest', 'as' => 'cleaner.password.reset', 'uses' => 'Auth\CleanerController@password_reset']);
//Route::match(['get', 'post'], '/cleaner/api', ['middleware' => 'guest', 'as' => 'cleaner.api', 'uses' => 'Auth\CleanerController@api']);


/*
* Cleaner
*/

Route::match(['get', 'head'], '/cleaner', ['as' => 'cleaner', 'middleware' => 'guest', 'uses' => 'Auth\CleanerController@loginForm']);
Route::post('/cleaner/login', ['as' => 'cleaner.login', 'uses' => 'Auth\CleanerController@login']);

Route::group(['prefix'=>'cleaner', 'middleware' => 'auth'], function()
{
    Route::get('/main', ['middleware' => 'auth', 'as' => 'cleaner.main', function(){ return redirect()->route('cleaner.tabel'); }]);
    //Route::get('/tabel', ['middleware' => 'auth', 'as' => 'cleaner.tabel', 'uses' => 'cleaner\TabelController@index']);
    Route::get('/tabel/{mobile?}', ['middleware' => 'auth', 'as' => 'cleaner.tabel', 'uses' => 'cleaner\TabelController@index']);
    //Route::get('/mtabel', ['middleware' => 'auth', 'as' => 'cleaner.mtabel', 'uses' => 'cleaner\TabelController@index']);
    
    Route::get('/mutual_settlements', ['as' => 'cleaner.mutual_settlements', 'uses' => 'cleaner\CommonController@mutual_settlements']);
    Route::get('/calendar', ['as' => 'cleaner.calendar', 'uses' => 'cleaner\CommonController@calendar']);

    Route::match(['get', 'post'], '/anketa/edit', ['middleware' => 'auth', 'as' => 'cleaner.anketa.edit', 'uses' => 'cleaner\AnketaController@edit']);
    Route::get('/anketa/show', ['as' => 'cleaner.anketa.view', 'uses' => 'cleaner\AnketaController@show']);

    Route::get('/departures', ['as' => 'cleaner.departures', 'uses' => 'cleaner\DepartureController@index']);
    Route::get('/departures/current', ['as' => 'cleaner.departures.current', 'uses' => 'cleaner\DepartureController@current']);

    Route::get('/orders', ['as' => 'cleaner.orders', 'uses' => 'cleaner\OrderController@index']);

app/Models/OrderCompany.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Storage;
use Image;

class OrderCompany extends Model
{
	use SoftDeletes;

	protected $table = 'order_companies';

	protected $fillable = [
		'name',
		'phone',
		'email',
		'site',
		'comments',
		'inn',
		'short_company_name',
		'full_company_name',
		'address',
		'ogrn',
		'kpp',
		'date_register',
		'okpo',
		'oktmo',
		'director',
		'buhgalter',
		'company_dir_fio',
		'user_id',
		'bank_name',
		'bik',
		'checking_account',
		'cor_account',
		'typ', 
		'logo',
		'building',
		'housing',
		'office'
	];

	protected $dates = ['deleted_at'];

	public static $logo_path = 'assets/imgs/order_companies/';
	public static $logo_path_preview = 'assets/imgs/order_companies/preview/';

	protected static $size_preview_width = 180;
	protected static $size_preview_height = 200;


	public function orders() {
		return $this->hasMany('App\Models\Order', 'order_company_id');
	}

	public function user()
	{
		return $this->belongsTo('App\User', 'user_id');
	}

	public function datePicker() {
		if($this->date_register && $this->date_register!='0000-00-00') {
			return (new \Date($this->date_register))->format('d.m.Y');
		} else {
			return '';
		}
	}
	
	//logo
	public static function saveImg($request = null, $url = null)
	{
		$arFiles = [];
		//URL в приоритете
		if(!empty($url)) {
			/*if (filter_var($url, FILTER_VALIDATE_URL) === FALSE) {
                return '';
            }
            $ext = pathinfo($url, PATHINFO_EXTENSION);
            $filename = time().'_'.str_random(5).'.'.$ext;

            Storage::disk('public')->put(self::$img_path.$filename, file_get_contents($url));
            $sizes = getimagesize(public_path(self::$img_path).$filename);*/
		} else {
			//dd($request->all());
			if( $request->hasFile('logo') && $request->file('logo')->isValid() ) {
				$sizes = getimagesize($request->file('logo')->getRealPath());
				$filename = time().'_'.str_random(5).'.'.$request->file('logo')->getClientOriginalExtension();
				$request->file('logo')->move(public_path(self::$logo_path), $filename);

				//preview
				Image::make(public_path(self::$logo_path).$filename)
					->fit(min(self::$size_preview_width, $sizes[0]), min(self::$size_preview_height, $sizes[1]), function ($constraint) {
						$constraint->upsize();
					})
					->save(public_path(self::$logo_path_preview).$filename);

				$arFiles['logo'] = $filename;
			}
		}

		return $arFiles;
	}

	public function deleteImg() {
		if(!$this->logo) {
			return false;
		}

		Storage::disk('public')->delete([
			$this->getImgPath('logo').$this->logo,
			$this->getImgPreviewPath('logo').$this->logo,
		]);

		return true;
	}

	public function getImgPath($typ){
		switch ($typ) {
			case 'logo':
				return self::$logo_path;
				break;
		}

	}

	public function getImgPreviewPath($typ){
		switch ($typ) {
			case 'logo':
				return self::$logo_path_preview;
				break;
		}
	}

	public function getPreviewSize($attribute = 'width'){
		$attribute = 'size_preview_'.$attribute;
		return self::$$attribute;
	}
}

resources/views/admin/order_companies/contact.blade.php
<style>
    .dash-table>table>thead td {
        font-weight: 600;
        font-size: 12px;
        white-space: nowrap;
    }
</style>


<div class="dash-table" data-item-check="wrap">
    <table>
        <colgroup>
            {{--<col class="tbl-check">--}}
            <col class="tbl-number">
            <col class="tbl-title">
            <col class="tbl-contact">
            {{--<col class="tbl-budget">
            <col class="tbl-tasks">--}}
            <col class="tbl-typepay">
            <col class="tbl-datecreate">
        </colgroup>
        <thead>
        <tr>
            {{--<td>
                <label class="o-input-box-replaced">
                    <input type="checkbox" name="items[]" tabindex="0" data-item-check="all-current"><span class="o-input-box-replaced-check"></span>
                </label>
            </td>--}}
            <td>
                {{--<a class="tbl-heads-link" href="#">ФИО</a>--}}
                ФИО
            </td>
            <td>
                {{--<a class="tbl-heads-link" href="#">Должность</a>--}}
                Должность
            </td>
            {{--<td><a class="tbl-heads-link" href="#">Компания</a></td>--}}
            <td>Телефон</td>
            {{--<td>
                <a class="tbl-heads-link" href="#">Сумма</a>
            </td>
            <td><a class="tbl-heads-link" href="#">Баланс</a></td>--}}
            <td>
                {{--<a class="tbl-heads-link" href="#">Email</a>--}}
                Email
            </td>
            <td>
                {{--<a class="tbl-heads-link" href="#">Дата создания</a>--}}
                Дата создания
            </td>
            <td>
                {{--<a class="tbl-heads-link" href="#">Ответственный</a>--}}
                Ответственный
            </td>
        </tr>
        </thead>
        <tbody>
        @foreach($company_contacts as $item)
            <tr>
                {{--<td>
                    <label class="o-input-box-replaced"><input type="checkbox" name="items[]" tabindex="0" data-item-check="current"><span class="o-input-box-replaced-check"></span></label>
                </td>--}}
                <td>
                    <a href="{{route('admin.order_contacts.edit', $item->id)}}">{{$item->name}}</a>
                </td>
                <td>
                    {{$item->post}}
                </td>
                <td>
                    @foreach($item->phones as $phone)
                        {{$phone->phone}}<br>
                    @endforeach
                </td>
                {{--<td>{{number_format($item->orders->sum('amount'), 0, ',', ' ')}}</td>
                <td>

                </td>--}}
                <td>
                    @foreach($item->emails as $email)
                        {{$email->email}}<br>
                    @endforeach
                </td>
                <td>
                    {{date('d.m.Y h:i', strtotime($item->created_at))}}
                </td>
                <td>
                    <a href="{{route('admin.users.edit', $item->user_id)}}">{{$item->user->fio()}}</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/admin/order_companies/create.blade.php
@extends('admin.layout')
@section('main')
    {{--for ymap--}}
    <script src="/assets/admin_new/js/jquery.min.js"></script>
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <script src="//api-maps.yandex.ru/2.1/?lang=ru_RU&load=SuggestView&onload=onLoad"></script>
    <script src="/assets/admin_new/js/ymaps.js?45"></script>
    <script>
        function onLoad (ymaps) {
            var suggestView = new ymaps.SuggestView('suggest');
        }
    </script>

    <div class="dash-container">

        @include('admin.message')

        <div class="dash-content">
            <div id="dash-kp">
                {{--<ul class="dash-kp-nav">
                    <li><a href="#" data-tab="dash-kp" data-findtab="kp-tabbox-main" @if(Request::get('tab') != 'staff') class="current" @endif>Основное</a></li>
                    <li><a href="#" data-tab="dash-kp" data-findtab="kp-tabbox-contact">Контакты</a></li>
                    <li><a href="#" data-tab="dash-kp" data-findtab="kp-tabbox-orders">Заказы</a></li>
                    <li><a href="#" data-tab="dash-kp" data-findtab="kp-tabbox-offers">Предложения</a></li>
                    <li><a href="#" data-tab="dash-kp" data-findtab="kp-tabbox-invoices">Счета</a></li>
                    <li><a href="#">Договора</a></li>
                    <li><a href="#">Письма</a></li>
                    <li><a href="#" data-tab="dash-kp" data-findtab="kp-tabbox-requisites">Реквизиты</a></li>
                    <li><a href="#">Статистика</a></li>
                </ul>--}}

                <div class="dash-kp-content">
                    <div class="dash-kp-col col-left">
                        <form class="form-horizontal" role="form" action="{{route('admin.order_companies.store')}}" method="POST" enctype="multipart/form-data">
                            <input name="_token" type="hidden" value="{{csrf_token()}}">
                            <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                            <input type="hidden" name="name" value="{{old('name')}}">

                            @if(Request::has('route'))
                                <input name="route" type="hidden" value="{{Request::input('route')}}">
                            @endif

                            @if(Request::has('order_name'))
                                <input name="order_name" type="hidden" value="{{Request::input('order_name')}}">
                            @endif

                            @if(Request::has('contact_name'))
                                <input name="contact_name" type="hidden" value="{{Request::input('contact_name')}}">
                            @endif

                            @if(Request::has('amount'))
                                <input name="amount" type="hidden" value="{{Request::input('amount')}}">
                            @endif

                            <div class="o-tabs-box kp-tabbox-main @if(Request::get('tab') != 'staff') current @endif" data-tab-box>
                                @include('admin.order_companies.tab_main')
                            </div>

                            <div class="page-kp-form-bottom-button">
                                {{--<span class="page-kp-form-button bgs-green">Сохранить</span>--}}
                                <button class="page-kp-form-button bgs-green" type="submit">Сохранить</button>
                                <span class="page-kp-form-button bgs-orange">Обновить</span>
                            </div>

                        </form>
                    </div>

                    <div class="dash-kp-col col-right">
                        <div class="kp-yamap-position" id="side-ya-map">
                            <div style="top:50px" class="kp-yamap-position-btn-close"><span class="icon-btn-box-close"></span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/order_companies/orders.blade.php
<div class="dash-table" data-item-check="wrap">
    @can('add', new App\Models\Order())
        <div class="ibox-tools" style="float: right;">
            <a href="{{route('admin.orders.create').'/?company_id='.$company->id}}" class="btn btn-success btn-xs">
                <i class="fa fa-plus"></i>
                Добавить заказ
            </a>
        </div>
    @endcan

    @if( !(sizeof($company_orders) > 0) )
        <p><i>Заказов пока нет...</i></p>
    @else
        <table>
                <colgroup>
                    {{--<col class="tbl-check">--}}
                    <col class="tbl-number">
                    <col class="tbl-title">
                    <col class="tbl-contact">
                    <col class="tbl-budget">
                    <col class="tbl-tasks">
                    <col class="tbl-typework">
                    <col class="tbl-typepay">
                    <col class="tbl-datestart">
                    <col class="tbl-step">
                    <col class="tbl-pay">
                    <col class="tbl-responsible">
                    <col class="tbl-datecreate">
                </colgroup>
                <thead>
                <tr>
                    {{--<td>
                        <label class="o-input-box-replaced"><input type="checkbox" name="items[]" tabindex="0" data-item-check="all-current"><span class="o-input-box-replaced-check"></span></label>
                    </td>--}}
                    <td>№</td>
                    <td>Название</td>
                    <td>Контакт</td>
                    <td><a class="tbl-heads-link" href="#">Бюджет, руб</a></td>
                    <td>Задачи</td>
                    <td>Вид работ</td>
                    <td>Вид оплат</td>
                    <td><a class="tbl-heads-link type-up" href="#">Дата начала</a></td>
                    <td>Этап заказа</td>
                    <td>Оплата</td>
                    <td>Ответственный</td>
                    <td><a class="tbl-heads-link" href="#">Дата создания</a></td>
                </tr>
                </thead>
                <tbody>
                @foreach($company_orders as $order)
                    <tr>
                        {{--<td>
                            <label class="o-input-box-replaced"><input type="checkbox" name="items[]" tabindex="0" data-item-check="current"><span class="o-input-box-replaced-check"></span></label>
                        </td>--}}
                        <td>{{$order->number}}</td>
                        <td>
                            <a href="{{route('admin.orders.edit', $order->id)}}">{{$order->name}}</a>
                        </td>
                        <td>
                            {{@$order->contacts()->first()->name}}
                            @if(isset($order->orderCompany))
                                <span class="tbl-block-company">“{{$order->orderCompany->name}}”</span>
                            @endif
                        </td>
                        <td>{{number_format($order->amount, 0, ',', ' ')}}</td>
                        <td>Подготовить коммерческое предложение</td>
                        <td>
                            @if( isset($order->calculator) )
                                {{--{{dd($order->calculator)}}--}}
                                {{--{{dump(get_object_vars(\GuzzleHttp\json_decode($order->calculator))['typ'])}}--}}
                                @if(get_object_vars(\GuzzleHttp\json_decode($order->calculator))['typ'] == 82)
                                    ген. уборка
                                @else
                                    послестрой
                                @endif
                            @endif
                        </td>
                        <td>{{--Безналичный--}}</td>
                        <td>{{date('d.m.Y', strtotime($order->date))}}</td>
                        <td>
                                   <span class="pseudo-select" data-pseudo="wrap">
                                       @php
                                           $bg_status_class = '';
                                           switch ($order->status) {
                                               case 'first':
                                                   $bg_status_class = 'bgs-first';
                                                   break;
                                               case 'agree':
                                                   $bg_status_class = 'bgs-agree';
                                                   break;
                                               case 'agreed':
                                                   $bg_status_class = 'bgs-agreed';
                                                   break;
                                               case 'confirmed':
                                                   $bg_status_class = 'bgs-confirmed';
                                                   break;
                                               case 'work':
                                                   $bg_status_class = 'bgs-work';
                                                   break;
                                               case 'performed':
                                                   $bg_status_class = 'bgs-performed';
                                                   break;
                                               case 'final_positive':
                                                   $bg_status_class = 'bgs-final_positive';
                                                   break;
                                               case 'final_negative':
                                                   $bg_status_class = 'bgs-final_negative';
                                                   break;
                                           }
                                       @endphp
                                       <span class="pseudo-select-txt o-btn {{$bg_status_class}}" data-pseudo="title" tabindex="0">{{$order->statusName()}}</span>
                                       <span class="pseudo-select-drop" data-pseudo="drop">
                                            <span data-order_id="{{$order->id}}" data-value="first" data-class="bgs-first" @if($order->status == 'first') class="current" @endif>Первичный контакт</span>
                                            <span data-order_id="{{$order->id}}" data-value="agree" data-class="bgs-agree" @if($order->status == 'agree') class="current" @endif>Согласовать</span>
                                            <span data-order_id="{{$order->id}}" data-value="agreed" data-class="bgs-agreed" @if($order->status == 'agreed') class="current" @endif>Согласованно</span>
                                            <span data-order_id="{{$order->id}}" data-value="confirmed" data-class="bgs-confirmed" @if($order->status == 'confirmed') class="current" @endif>Подтверждено</span>
                                            <span data-order_id="{{$order->id}}" data-value="work" data-class="bgs-work" @if($order->status == 'work') class="current" @endif>В работе</span>
                                            <span data-order_id="{{$order->id}}" data-value="performed" data-class="bgs-performed" @if($order->status == 'performed') class="current" @endif>Работы выполнены</span>
                                            <span data-order_id="{{$order->id}}" data-value="final_positive" data-class="bgs-final_positive" @if($order->status == 'final_positive') class="current" @endif>Успешно реализовано</span>
                                            <span data-order_id="{{$order->id}}" data-value="final_negative" data-class="bgs-final_negative" @if($order->status == 'final_negative') class="current" @endif>Не реализовано</span>
                                       </span>
                                   </span>
                        </td>
                        <td>
                                   <span class="pseudo-select" data-pseudo="wrap">
                                      <span class="pseudo-select-txt" data-pseudo="title" tabindex="0">{{\App\Models\Order::$payStatuses[$order->pay_status]}}</span>
                                      <span class="pseudo-select-drop" data-pseudo="drop">
                                         <span data-order_id="{{$order->id}}" data-value="payed" @if($order->pay_status == 'payed') class="current" @endif>Оплачен</span>
                                         <span data-order_id="{{$order->id}}" data-value="nopayed" @if($order->pay_status == 'nopayed') class="current" @endif>Не оплачен</span>
                                         <span data-order_id="{{$order->id}}" data-value="partpay" @if($order->pay_status == 'partpay') class="current" @endif>Частично оплачен</span>
                                      </span>
                                   </span>
                        </td>
                        <td>
                            @if($order->responsible_users()->count() > 0 )
                                {{$order->responsible_users()->first()->fio()}}
                            @endif
                        </td>
                        <td>{{date('d.m.Y H:i', strtotime($order->created_at))}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
    @endif

</div>